In [8]:
# Importacion de Librerias

import pandas as pd

In [9]:
# Usando la ruta esto permite que python busque el documento en otra carpeta sin exponer nuestras rutas privadas

ruta_match = '../data/raw/Match.csv'
df_partidos = pd.read_csv(ruta_match)

In [10]:
df_partidos.head()

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,...,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,...,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,...,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,...,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,...,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,...,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67

In [11]:
# Al ser una base de datos relacional podemos filtrar los partidos a solo la liga espanola usando el country id o league id
df_spain = df_partidos[df_partidos['league_id'] == 21518].copy()

In [12]:
print(df_spain)

          id  country_id  league_id     season  stage                 date  \
21517  21518       21518      21518  2008/2009      1  2008-08-30 00:00:00
21518  21519       21518      21518  2008/2009      1  2008-08-31 00:00:00
21519  21520       21518      21518  2008/2009      1  2008-08-31 00:00:00
21520  21521       21518      21518  2008/2009      1  2008-08-31 00:00:00
21521  21522       21518      21518  2008/2009      1  2008-08-31 00:00:00
...      ...         ...        ...        ...    ...                  ...
24552  24553       21518      21518  2015/2016      9  2015-10-25 00:00:00
24553  24554       21518      21518  2015/2016      9  2015-10-24 00:00:00
24554  24555       21518      21518  2015/2016      9  2015-10-26 00:00:00
24555  24556       21518      21518  2015/2016      9  2015-10-24 00:00:00
24556  24557       21518      21518  2015/2016      9  2015-10-23 00:00:00

       match_api_id  home_team_api_id  away_team_api_id  home_team_goal  ...  \
21517        530023             10267              8661               3  ...
21518        530084              8371             10205               1  ...
21519        530085              9783              8633               2  ...
21520        530086              8388              8634               1  ...
21521        530087              8696              8302               1  ...
...             ...               ...               ...             ...  ...
24552       2030167              9906             10267               2  ...
24553       2030168              9864              9783               2  ...
24554       2030169              8315              9869               3  ...
24555       2030170              7878              8603               1  ...
24556       2030171              8370              8558               3  ...

        SJA   VCH   VCD   VCA   GBH   GBD   GBA   BSH   BSD   BSA
21517  5.00  1.65  3.40  4.50  1.75  3.30  5.00  1.67  3.40  5.00
21518  2.60  2.90  3.20  2.25  2.75  3.20  2.50  2.80  3.25  2.30
21519  1.90  3.25  3.25  2.00  3.50  3.20  2.10  3.25  3.25  2.10
21520  1.57  7.00  3.75  1.45  6.50  3.75  1.53  5.50  3.75  1.53
21521  2.30  2.70  3.10  2.40  2.75  3.25  2.45  2.70  3.25  2.38
...     ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
24552   NaN  1.57  4.00  7.00   NaN   NaN   NaN   NaN   NaN   NaN
24553   NaN  2.30  3.40  3.40   NaN   NaN   NaN   NaN   NaN   NaN
24554   NaN  1.55  4.20  7.00   NaN   NaN   NaN   NaN   NaN   NaN
24555   NaN  2.30  3.40  3.30   NaN   NaN   NaN   NaN   NaN   NaN
24556   NaN  2.20  3.60  3.50   NaN   NaN   NaN   NaN   NaN   NaN

[3040 rows x 115 columns]

# Ahora que tenemos la liga procedemos con el proceso de limpieza en las demas tablas

In [23]:
# Filtrar equipos de la liga espanola por ID
equipos_ids = pd.concat([
    df_partidos['home_team_api_id'], 
    df_partidos['away_team_api_id']
]).unique()

df_equipo = pd.read_csv('../data/raw/Team.csv')
# Nos quedamos solo con los equipos que jugaron en España
df_equipos_laliga = df_equipo[df_equipo['team_api_id'].isin(equipos_ids)]

In [24]:
# Revisamos la correcta ejecucion
print(f"Equipos españoles filtrados: {len(df_equipos_laliga)}")

Equipos españoles filtrados: 299

In [25]:
df_equipos_laliga.head()

   id  team_api_id  team_fifa_api_id     team_long_name team_short_name
0   1         9987             673.0           KRC Genk             GEN
1   2         9993             675.0       Beerschot AC             BAC
2   3        10000           15005.0   SV Zulte-Waregem             ZUL
3   4         9994            2007.0   Sporting Lokeren             LOK
4   5         9984            1750.0  KSV Cercle Brugge             CEB